export * from './IBaseObject';
export * from './INullObject';
export * from './IBooleanObject';
export * from './INumericObject';
export * from './IStringObject';
export * from './INameObject';
export * from './IArrayObject';
export * from './IDictionaryObject';
export * from './IStreamObject';
